management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
spring:
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
  mustache:
    check-template-location: false
okta:
  oauth2:
    issuer: '{cipher}AQBa0iaGOIdAPtYLn4cj3ABNrSkl32S3QeRGvMPKMc3JZigXQuxl7ud/i+068p8yL80m8PRysETPZlYhwljSZGbn0I8gCYPaSXMqZHGcv2rb6FV7H6ZMcyaosqvGFGh1bkR38swrCnOuAeB3NufGXFWwhOJADHcG3HLZ7Tq6bYySJ9apE6aZ3GwHXFoCAYJrpidfKRTWODqK7Oj04JE1Ks9HWcjUAG77xs8CdXX4Z5rw0YTqhpibVeLZQoyeDF6vEfPzrkuKWZVfuRTNQY8mq4Ef8X236m0MaVvK/NDWzCCrYrwTCmAx+6hL7WMlnYn3BgIBCLFmUKeuy2sNxW/dgMevh0YTMMgHzVwXmjAUN1GxZKBHrGdoCiIacnTaMOS0hUeSHtPOnJaAd2PHyk+iSC2NLkrwqQ8C4z+f8vwjYVcZMA'
    client-secret: '{cipher}AQABHMgCvjoefBKJWt3Bca3c84PGwiWvkEjsPEHrUtDiTp3mU47HPru8SO0WObOaBy+oKDY65hScQ+7Bg3ohf3RjkwErDj1p/a/U7Ztm1mNTY0otY3ijmFilVk0pw2+ttjNAXQPTjrr1loaGCUPeq+lPSlXjambQea6nQOjnjOxJyJbbzFYztpBsq0D7U3MSQLHpPKbp3gaY9f7kukIyS+8YY6uMUCepcgOjpgCTzHBPKOM+oKNGv8wHmlBg+65lnlSEqSwAh8PeTmXZ7vRRbo0lFf/C85u9Jm/u/so28qV5HkJzhd8IQn+VxPGhrBi0tkZJ5MFTXhWP8I0439GfBmMEEFq/QATKzDSUsP/ZSX5VrGU3R/l/qoQm+BIWyj3KQoHRza6feh91bZy+qQc6hB2CfQ/joWNlQUs0Qr6sIzJauA'
    client-id: '{cipher}AQCP9N4wQfqRuSn+s/Ay4MNR32JnyzPpx61ba1XKHym94wzqUsLhV+cCF8Ad/y2A4ARyu38Rh3uPFc3Hrzr2NDQfHovjuT5seePKPO845l8kdiMSq0uQW/O1kVkaY5w7ZsOniiXgOkfM+l8mMekW9Rf+MSj/R96NevSv1LI73szEXqLVYl9s39uf4ZMdZUqG++tBFoOekCiDyzAz8PcPRn5YReVY8io+02AyLDPQ7sMMGanibLqQLgXpifZ3RvcwFqGK/exaOhQEQH3TGcp6UMXmmg9+wqA5mqZ6yyjaRCcPmDV9lbywbnBvVOTbzaU+mHCYXIwbD/Tvo+DcEIeYXBycBN/rEM9/VbV/nplMQ9fMY5sjxYbPDLeXiX0gLq4uQsDQDn6IYgbY9iVcjq/vwP6e'
  client:
    token: '{cipher}AQAYMxCJltZwdCMa1ojdFSwPhLSSSgW1k590EPEbby/KkHkfHh5Jyb+rtV/ELFgeBrP/5L2LxxtIDNW6X+4SVDKN7BSV5CHOuxTfhfZ7yyl7fYBmGKwsTLRzzYInQ9DGh2ncFfQWZya2tK75G5bSsGjSZ3rIh4hk1eC+4M+m0aLPEUMNbS40pa5K9SappowYAESNbU6N+SDX1s7CAUpFc3gRK4PbwloLsi5zqC2zX0dAQdQixnlGs/8FoJwHyBHxG7GxoLiFqjWA9nMHAHQvpAyLffTSj4ZBpu88jRpA5a/O6yq+JDBxV7MPn4U7LjGO9jgbY5inxYh+/dwECv19us9quaMPFOPHkNpR88m1WjiZ6EPw71YmhCnV5vMdA+TcZqmc+XeXp2sbf7hUtOKyXZuRp+vUgRkwYva5A1yvlCj+nTdcYAQXjALrSfso+TZ39gE'
    orgUrl: '{cipher}AQBfikJknrnsGUyClFoECx3pHjUd57KoxwVD7gtWx/7xT/LiIB/Pn3TSai6U7boYL42+m0luUIgizFi3TUruCbF7w+Rmd/AM4GD18u6gIrhW1hA70EKv90M5bJ4qcKEff7O8+VJVwWwpKZgL/Xii/8uaE4IkkIS3XVZQ267mTxb+l4VWh7htp/4oCFU9BYKuy+39/kf+zFf3KQHBIophFS/+0hiHzaTjGQ6q5f2JePSns4xpuN/EoIkrLeQzirxxWjfbFZvnUz1XRXttnlq50C4aWNWuA+GaUn+YorhqUst0mNV7Bm0kEv6aZOVb87eAS+2x9Wl49uPyhqAFYXwRUz6NJKfa8lngo+ls64MVVrn951u/gr0/Z4mwjcOpxWnPU+ZrGKLxnsHGR9OGRjm6hD0j'
logging:
  level:
    root: INFO
    org:
      springframework: WARN
    com:
      noslen:
        adminservice: INFO