#.env:
#    directory: ../
#    filename: .okta.env
#    ignoreIfMissing: true

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: {cipher}b2c04dcbd25c539399855dfd79cd4f00fee512ace8bef69d6363f09cd08a729c2ba20196e307d4a4b415aae1379a5d209218499b803d280c2456f02d4b93e060
            user-name-attribute: email
        registration:
          okta:
            client-id: {cipher}1206d8955c158a65d4e96463c7a78a68237763866d99ef87a3bce7dd2e8749310ac1a3b97bd6393fa31e0b25cb0848d5
            client-secret: {cipher}7482cce38d07a0821be898d1213143cba46d6e83f419261ed2f7ad4022608d97fef68b3071f8591776c94ff9fdfaa9b2fdf6573ec7bf2dad973eca3ad41d6144
            scope:
              - email
              - openid
              - profile

  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:5001/
          predicates:
            - Path=/api/lesson/**
          filters:
            # Include the access token as a Bearer token
            - TokenRelay=
        - id: troopers-mvc
          uri: http://localhost:8000/
          predicates:
            - Path=/mvc/**
          filters:
            - SaveSession=


#    session:
#        store-type: redis
#        redis:
#            flush-mode: on-save
#            namespace: spring:session



