spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:5001/
          predicates:
            - Path=/api/lesson/**
          filters:
            - TokenRelay=
        - id: admin-service
          uri: http://localhost:5002/
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=
okta:
  oauth2:
    issuer: '{cipher}e342d63f08b35b21180353071f27cf8ee7f9ebf83402caf48518812b6578df58bd2c67bc77e6a796100c3568be3e3216c5e2ebc9848dddaaad432e71d33260b7'
    client-secret: '{cipher}4e9b8fd42f3fc3e95a99d5e6cd5cf9f36d646ccd95b6420da927f04adbe7d16f2fb9cfd02ce76fe4a1662c3fb855744c8fae4d009f4a578b48f5a416f58f825a'
    client-id: '{cipher}8a36be7d0843edb4f968af444d0d2d3d282a2a75ec3f4e848ebe8039a5c4facc5471768902ea23174dcb80e59cd8e148'
logging:
  level:
    root: WARN
    org:
      springframework: INFO