server:
  port: 8080
  ssl:
    key-alias: www.turbolessons.com
    key-store: /tmp/www.turbolessons.com.keystore
    key-store-password: '{cipher}3b6994c302f49b0a8ed942f140218cf22f01c3ed8437bb778cdb0511ac6b1624'
    key-password: '{cipher}3b6994c302f49b0a8ed942f140218cf22f01c3ed8437bb778cdb0511ac6b1624'
spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/lessons/**
          filters:
            - TokenRelay=
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/users/**, /api/users
          filters:
            - TokenRelay=
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /ws/messages/**
          filters:
            - TokenRelay=
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - TokenRelay=
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/video
          filters:
            - TokenRelay=
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8761/eureka}
    healthcheck:
      enabled: true
okta:
  oauth2:
    issuer: '{cipher}e342d63f08b35b21180353071f27cf8ee7f9ebf83402caf48518812b6578df58bd2c67bc77e6a796100c3568be3e3216c5e2ebc9848dddaaad432e71d33260b7'
    client-secret: '{cipher}4e9b8fd42f3fc3e95a99d5e6cd5cf9f36d646ccd95b6420da927f04adbe7d16f2fb9cfd02ce76fe4a1662c3fb855744c8fae4d009f4a578b48f5a416f58f825a'
    client-id: '{cipher}8a36be7d0843edb4f968af444d0d2d3d282a2a75ec3f4e848ebe8039a5c4facc5471768902ea23174dcb80e59cd8e148'
logging:
  level:
    root: DEBUG
    org:
      springframework: INFO
    com:
      noslen:
        apigateway: DEBUG