spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: '{cipher}f211af020a7b84e951b6c9aea5fb57bec43ac63b08adbb0005cbac191c59bcfb90cec82efe6bdf0c1987b4982006557d60d6356594a8f6d3244fc75990c423f0'
      client:
        provider:
          okta:
            issuer-uri: '{cipher}b2c04dcbd25c539399855dfd79cd4f00fee512ace8bef69d6363f09cd08a729c2ba20196e307d4a4b415aae1379a5d209218499b803d280c2456f02d4b93e060'
            user-name-attribute: email
        registration:
          okta:
            client-id: '{cipher}1206d8955c158a65d4e96463c7a78a68237763866d99ef87a3bce7dd2e8749310ac1a3b97bd6393fa31e0b25cb0848d5'
            client-secret: '{cipher}7482cce38d07a0821be898d1213143cba46d6e83f419261ed2f7ad4022608d97fef68b3071f8591776c94ff9fdfaa9b2fdf6573ec7bf2dad973eca3ad41d6144'
            scope:
              - email
              - openid
              - profile
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:5001/
          predicates:
            - Path=/api/lesson/**
          filters:
            # Include the access token as a Bearer token
            - TokenRelay=
        - id: message-service
          uri: http://localhost:8000/
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=


