spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/lessons/**
          filters:
            - TokenRelay=
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/users/**, /api/users
          filters:
            - TokenRelay=
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /ws/messages/**
          filters:
            - TokenRelay=
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - TokenRelay=
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/video
          filters:
            - TokenRelay=
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    healthcheck:
      enabled: true
okta:
  oauth2:
    issuer: '{cipher}AQAhBQ9jU2jChLxMcpNvd+NcEPiOHa0kcd42+ocrG4dlsJfiupd22+5W2SLnIkZyI+c2NWh+FW5soUVuvtQ9RvZRYNrFLAwUnV8Bp3DkA9uZVoinoYyKcbFp0Atq+v6q14e817AWmuZoRr+SRC5ncjlewy438z7J4y7sssWMTsGeOF+wlNpW8o5PZe/WBtXIwi/vzX0ieipuOXEx6gD2CP7Uts3NZeh9zn50iNaEvCLmgGjLi+3I3bKX5CW3XjUovv4w073ma7YDCEJPY8r2cCAceO6xUuje9WnHkP5XgdiRMIKvCrlgJCqu6ooVML/m0Tyv86kGnvpsjYCOrzZ8zeq9XeH5aYANHFcKdsRB/UpDMG1u1doCJiaiEJeqIFIUhOp6C2FQjx24sP1qUlhugyE++jkENQP3wE58X9xEyPsAjw'
    client-secret: '{cipher}AQCzC5PQ33bzX6QU1hE4/oT/CAIFhLZN5cXkeapmk07CtewXjvBZa7Jt9GACbfKTUGbTHwWhJe9lB17Vx7gHlaBfJpfabDrJBzdg7ut3n7cRsCTBYtXskehVqC82G4BPunOAJ00F811/ra3SP7YXO4DfaPCnOG1yR4XzyXhpDjIz5IqlNQCMMdlQBAZoMCpD2Q41pk2pDa5AV6Q5hE7mo9Vraaku/WkvGpc6lQk3ntPCGP/+JpwH0Bv+Mne63gmgpwdJ+Ky/URBcAaP6cdhLN/Wl8Urx8Gz1iRzkS2R+QCQe5JLnclMHdZqQpLetxDZJh7tL02icejtu6ah/UzWUKtyvMYJd2Z3P+U9nbTvcS7sCF2Zz6qntxr8gIkDKitABfsI8fDRvD4d0LLA1PcAZXnq6hk5s5YZIe6NEKbvwA8ZN0w'
    client-id: '{cipher}AQCkNfM/oJ5FyXrmDRmV75vrULFlz6xA7gOt9CdtZ4+39DvXTw2hrJTUHb0v3x85UB6v1iNd2XhZHp8AtTUg8YDk1Vqf7nIajYfx6X6P7G5yq8yNiCLqYtCzNv3CE1RqvFhe6v0ZFvgbkoLc0AQ0MVK10sg+BJQLo5r9UQYf2XfoSsCkcIlxVZwsIpG0ZCax2ydVfAerdykGLzbk64/pfbR7f8sk0diqj5HMGjCEE4arc4l4vBeipPJ7oQxcnmirq1Z+cTPuRlX4AqLYpZRWsOiBHMFP3BBP82PB/pYJIsazMi4cx2GMabcXUHDrJGLzadWRu65dPJRjaxlPIfgK7COnOr3qq6U2S1JhK1DST1yvA3uyaXAUfDxjK4Gz/26L9WfSMEhDRVnwuY/gEN3zMBwO'
logging:
  level:
    root: WARN
    org:
      springframework: INFO
    com:
      noslen:
        apigateway: DEBUG