spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/lessons/**
          filters:
            - TokenRelay=
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/users/**, /api/users
          filters:
            - TokenRelay=
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /ws/messages/**
          filters:
            - TokenRelay=
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - TokenRelay=
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/video
          filters:
            - TokenRelay=
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    healthcheck:
      enabled: true
okta:
  oauth2:
    issuer: '{cipher}AQAsab93sJoDw+44maPfc+NR7ppSTJ3Dydjb5ZC5O6qOdS6J84ugaOOmyG/MsBAbfVJSvNg2xRm/v61jNMw+jjFYeOsUwt5+GRNjUbe51N619zk4BxUETjdybACZO/5/YJ5yqsrWwGb63k6zSSjtwszwmHvM2xeQ0I3gLNqFugGudr8w1zSa/5c/guErUQ7VVBmuIPAGzPz7y2wQReFk1byXnllCtThhJAQ8Lk2Rgipcu9Y4bL0JVoU9eDRlEUINyUooSgTzVAcclirY1C/j2hdeZZm4Ua5UzvJgWy63Dc29Vugm4u83qG4cEW6OUnneeNMO4as8Q+ALz7yxhJKOpAw+8+RdqMjBvuoSlJfBbVvnIFZ5Mh/q3q8JJ+MMq6/C2MU/SoG00sMPL3iSsOswNyrGmrwWcCAt1DAwPc7Sl0086Q'
    client-secret: '{cipher}AQAE0rjzpojHzbuk4XUeP7yuCV6dw1fxHHvrY6tfQ6m4qkR5fwi3ze2WTnvurz7QBZYSeZXHy9TFoaNeXa3/PRm1QPciEEXOKiIapArFbA/1eVpwNA8llXXU+OkE+/6YwFGuYBKjkeWJSVJkT/D9qgKzWj9q1FnsCoRnOHy8CNeqcbGfjGJCETu5LWxcQjC8ZkkyzVDvcQ277b31YcqijamoKDiiofiWnMj5TYmKtu2F+N5nD7s4erHDGYo60Isv1eGCCo/GP0AJFTKGh3+j7istIaDIOerdlfynYkrI9KuUnA2S5T4b+Bn+JwXUB/YyhcWDOcqLdQqJlznc1LwpB7Wo8ys763k3dmK0z1iICWLz5OFMHTGeM36UWtDc4UTBnut4WBrj2m4p4V/YTYBmdX6HoWR9XnX3DmTSHMYm9e847Q'
    client-id: '{cipher}AQB7/EEs0dr0uyH0dCaKmIlfXtSzWwsVvshUIzQLkQDFw3jXn0mwcZIIjSMSwMBi2+TB8+pjTjCaopVe7BXpJJJFBCbR7r4fzzxURuKt0j+hbkwpfWAypOdm9CAUMYNGeO6W6q0lKXJuH7DA9cvCsd8QW+aJhHfUz0yrrxH5dCirIUdp7FUq2etxMhmso6NwQhrL/+Dfb1DTpc/fsa4RqBqXKsvlURqyA50TOp5xpHS4PlN153C8nMProzHHjO8B185J4vMOFg3cDqRktDZDcsezvfhYbm639dE1DS7rXQ2mSVFpcvPpv1aS1QxN5YXbk/OOZGsDJaxGB8/+vTb0nvbDWH0GxiheY1su93f2J237wTGjdqDXA/kXT3x3Yh+W88vFV/H/g+HtfkRBpiRZ7X16'
logging:
  level:
    root: WARN
    org:
      springframework: INFO
      springframework.cloud.netflix.eureka: DEBUG
      springframework.cloud.gateway: DEBUG
#    com:
#      noslen:
#        apigateway: DEBUG