server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/keycloak?autoReconnect=true&useSSL=false
    hikari:
      connection-test-query: SELECT 1
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
  keycloak:
    realm: lsa
    auth-server-url: http://localhost:8083
    ssl-required: external
    resource: event-service
    keycloak.credentials.secret: 3F2275wzaP7AkhEIeiOjePffT8eYruFs
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: noslen
      password: pass
    realmImportFile: lsa-realm.json

