server:
  port: 5001
spring:
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/eventplt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: '{cipher}38317c4bf83adb048baf67ba69f1ebb845f63491167cf3ff52c8f634a983c35dcd431ee2e04970dbf52bf16c7c998a47090eced7c4b272e6bb83c3598f870e8a'
