#server:
#  ssl:
#    key-alias: www.turbolessons.com
#    key-store: /tmp/www.turbolessons.com.keystore
#    key-store-password: '{cipher}3b6994c302f49b0a8ed942f140218cf22f01c3ed8437bb778cdb0511ac6b1624'
#    key-password: '{cipher}3b6994c302f49b0a8ed942f140218cf22f01c3ed8437bb778cdb0511ac6b1624'
eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry:8761/eureka/
spring:
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
  datasource:
    password: root_password
    url: jdbc:mysql://lessondb:3306/eventplt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
    open-in-view: false
  mustache:
    check-template-location: false
okta:
  oauth2:
    issuer: '{cipher}AQAhD9hxwdssoLNQpCFCc+y5T2OFsRxNmxOk1DujZ9xjafif8VFNTDTI6bzBZ+sCt5q/Ou8EEkC+kWXPDNkHE28N7g5Vnb1C5PZRdBLO+f7y39hvAaonLclWkXhshfmLWQBRv4iqFSyza/d+1c7B/9s2uaC1OUIVkq0kpuyV+uXgPtHi1faH68WkDaEQQTkKz9NccuFzjhnUby7UHVON1KnMS2CLCIfJmywuDeXXky+KvgPCdwjWM73xRvPow/8RbsfGcjYnFyI+7CpAUyR8W9wt+HdwM7HjrZAXXc5+EM8ek68MdSqIS8OWntu0+AnyYOCHgblqKtZApk3nuJrf8WFa4vDkg4FU8rHO2UWa/kauaZy4xqksH8eEu/F8bTHtkj1KDKc4BOzbgnXbpVMfdkswLqS6oYrTPXKH2qgndfVZFw'
    client-secret: '{cipher}AQDGoXi5BpaJ8tjlgUakjXaJwNGIA5sSoXF7aiaOkbK32KPWI9IyG+E1+B1wAkqLz0yHagzegcFSZUmS3p+LEnTfXJ5FbmOEVLMvEg5Kgyg7j7SHmfP0lTQNKg15O2XajO1AHBwhEIBrJ7h9Q7jUbGWGh2ddssPF350o4Rqc/Io3Ak1Y0xo08F26rAo+sCwbQguJKr61hHUo7wwJAArnqcLC2KztmoLw837CwAHm9/O0PIh2juc3VpZsMWSQL1UT2gl3dNfQdRzwDD3svf4QDa/3XyhnnUwKFLNUflRCUJmyihXKXlSOGEZpoeBcb3o8b94dzKx8sGWvMT+4oCZOHvBYADYTZFKsrfAiEZocgxVxtAhlbXi4dv/qIvRICN8EPhDMO8xsA0NiDq0XbrJu/Sm3KDUuozSrcB2SSVtHfqVu3g'
    client-id: '{cipher}AQC6esFAAJrh4S/bXqEjGyxfm6WCcbooIx7jGVkzvdpqmkKnGpYMAcyYDkHfg2DcqgNpUN8dfCz7W1Z0TTXDOBuPWSNcNdn21O4Axt6MIXAhjuIj2NO8bIEI57gse0ysxjVSIVgu0KsgeHbbymDauk9qvrVFHJrOJEpccVS6RO6henKa6caLg483HGcEr76IJSvuBmzzmTAYAnsRjxgmngwioObFVC2VbXsGmPZkhHYZ+rmzsXCugnOE12Xlf6OtE00WRBzWrVcpDi7Ck6Z931puUpdOVFN8eY3M9d32poBYPPspMzJj0yThnKZ/n4MMpcPklMjXrYyuMGp+IU2avJKNHBtjf7MKtL8RRI+KMRE3OAuxcu5QwBV9R3Rz7AYDhnLnsZchVWn7LJChAK5Ta/hQ'

