server:
  port: 8086
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
spring:
  config:
    discovery:
      enabled: true
      service-id: config-server
  application:
    name: gateway-service
  cloud:
    gateway:
      redis:
        enabled: false
      routes:
        - id: quotes
          uri: http://localhost:8085
          predicates:
            - Path=/quotes/**
          filters:
            - TokenRelay=
        - id: events
          uri: http://localhost:5001
          predicates:
            - Path=/api/lesson/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/lsa
        registration:
          quotes-client:
            provider: keycloak
            client-id: quotes-client
            client-secret: 0e082231-a70d-48e8-b8a5-fbfb743041b6
            scope:
              - email
              - profile
              - roles
              - openid
---
security:
  oauth2:
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8083/auth/realms/lsa
      registration:
        event-service:
          provider: keycloak
          client-id: event-service
          client-secret: 3F2275wzaP7AkhEIeiOjePffT8eYruFs
          scope:
            - email
            - profile
            - roles
            - openid
