eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: '{cipher}AQBRgp0t1f2dd+i+uobf95hFm/IZoHUtq9nfEAwztZmeBR5Z30Y/+Ir/n/dEmnJqabp7NYVSqlfB6m15I9VVvfgP7P2+Ixiylt4K1VDnEwWD1/ZCQsWmWshQ0RoqzjZjr6jTJfNsYJNut2jWeNt4UCZB55kU0yfLa1kxArql06n8b1RIGsE3CWfOzaahFz9Lljd8OJyCue0cLpmJQ4tC+nLuRykFmN20QLNUpuZBdHvPGSZLTI3JsC/82ZHzhLaH+DwpaK9jcDrseO23H/bHKPsdobHRkeIoDhnCzmb4iAFM78eIgZQCf5hh3LrNjuRbeMnBT0t9KLbgL1SFGIdjgH8HC5JtzjAhXM5MwthSCznM3cKyVUFYlaJu0pEn3YfeeJp7fiyH59Hgg5cFiuKXJcJHh6tvCDGC2AvINbBYKxxjcM5Ee0uYIHyYYMfQ+CVQuts='
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
  data:
    mongodb:
      uri: mongodb://root:example@messagedb:27017/lsa_message_plt?authSource=admin
  mustache:
    check-template-location: false
okta:
  oauth2:
    issuer: '{cipher}AQDWr46x2Vy/TMVtpEPLijimzPYPjxOsYVGxjcUClLXPepqnon4cxhm3sQzFohb/adEH7mz6Pb/w0gU5MqH5oVWTvqk1HSDtyRQHqZxSKYSvRrFmEa4ht35oMbyTR/X3TS9ZXEOJtwZCZpB1KOJwcDhMQ1fEHfCMgWV1lkqzXc6IlGmk/RSzaaCImQJyGzzzdSTn4vmftMEiVlX30aNSdhEEze1nLKgEgaf68m/4KEMAAkiwqv3JfrWk0ezWbKFZogOdsdYVxiQYLq9TnzhtoeKP0NR+ksCQbU+ovYfXmmpZW44KvnG/kcozhwWqzkWaxj4i5juXHJNzziQbUEK596iRoVkw+UR8dZVi1AbmM8OQr1xvYGZAemjNkD50uo9n5Cl+c4ouksnaFUu2EaBuVTDV6xyoETSgNm8OSPdHDTq7rw'
    client-secret: '{cipher}AQA1dvUiM+Fmk5qjcqOFx5hFdPAfzEwKHR6MzreQvaLQh8lt3fyQKCdtQawX0+e4NlPZVVg1rfgzHxKDWWrC47I8RVW9PcHPN/bR6IVbT30CjjLms4dSBAlLfuwmjef1TUGd7ChOGPmIvByA7JvLjSsTPBP3u+2QjvSZyJs1fhrfHiHNxyn6Xoc7plTQw+8YdIFyIXePuEJs7eotMF6Q4Q1K0c6eH+U902mnb30B2WOSUg7oNnT6Z5pBouOjmgYlFXfItUUBm6OUayarT+nCoTdPBeBlCliNMiRcu7jO++METEpTjYpYQtVaaOCtSyL/3iZsPk3M5SzWlchSNNbp/Zrckh5S9Xc9pbHpJX3xdsF+vbYIXkwJGWGLTqbtOLOZcHmUB6qUZg4AwfwGlt9RRGksbAvZpEhS3852iyawlqEp9A'
    client-id: '{cipher}AQAuispuaEJpgBTz4jkEqTnbHu7kMaWjAk2oBXn1V7R5UeRGQKg+rZgtLfcQDuHULzFSKrCk8BeZqV0+j/Xh1gIb/eZ386Bi094XDOMukmXjUDzqjqSm842xI8P4ZZCKVA73ypULN2DbY4VVAcQaMjtDoOjO6TPRnapdzBczbSQ1V6fpR22vpyLEpIpIr2GYOyK7MhCEbbyde9ZhFm6xRFytw4lNYnDf62ftPFay8uNWojD0F587eJPJkQsXW9FVfbFGWMTqNoxYCr4XYAe22lw0etGuF8OkYjctMVNWFyu0tLp9howjFChAV8zmTBqBtwOUG5Ix73P0H7RmaiZfNofpOWLlPr32ET7suuWg1cTeoJatCv4rp6ADeCMdhwD4um9SwO3wMTFGaNNoddKqFE8h'
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
    com:
      noslen:
        messageservice: DEBUG